import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/header";
import Footer from "./components/footer/footer";
import { Inter, Poppins } from "next/font/google";
import { getTopCategories } from "./utils/api/category";
import { browseCategoriesWithSub } from "./utils/api/browseCategory";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Academuz",
  description: "Generated by create next app",
};

// RootLayout component with async data fetching
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Fetch categories and subcategories server-side
  const categories = await getTopCategories(); // Fetching top categories
  const browsingCategory = await browseCategoriesWithSub(); // Fetching categories with subcategories

  return (
    <html lang="en">
      <head>
        {/* Font Awesome CDN */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-K6BlahBlah..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>

      <body className={`${inter.variable} ${poppins.variable}`}>
        {/* Pass the fetched data to Header and Footer */}
        <Header browsingCategory={browsingCategory} />
        {children}
        <Footer categories={categories} />
      </body>
    </html>
  );
}
