import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/header";
import Footer from "./components/footer/footer";
import { Inter, Poppins } from "next/font/google";
import { getTopCategories } from "./utils/api/category";
import { browseCategoriesWithSub } from "./utils/api/browseCategory";
import { CartProvider } from "../context/CartContext";
import { CartDrawerProvider } from "../context/CartDrawerContext"; // ✅ Import provider
import { Toaster } from "react-hot-toast";
import CartDrawerContainer from "./components/Header/CartDrawerContainer";
import type { ReactNode } from 'react';
import RouteProgress from "./components/Routeprogress/RouteProgress";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Academuz",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const categories = await getTopCategories();
  const browsingCategory = await browseCategoriesWithSub();

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-K6BlahBlah..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={`${inter.variable} ${poppins.variable}`}>
        <CartProvider>
          <CartDrawerProvider> {/* ✅ Wrap with provider */}
          <RouteProgress />
            <Header browsingCategory={browsingCategory} animate={[]} />
            <Toaster position="top-center" />
            <CartDrawerContainer />
            {children}
          </CartDrawerProvider>
        </CartProvider>
        <Footer categories={categories} />
      </body>
    </html>
  );
}
